name: Build

on:
    push:
        branches: [ "*" ]
    pull_request:
        branches: [ "*" ]

permissions:
    contents: read

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   name: Prepare
                run: sudo chown -R $USER:$USER ${{ github.workspace }}

            -   uses: actions/checkout@v3

            -   name: Validate composer.json and composer.lock
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Run unit tests
                run: vendor/bin/codecept run unit

            -   name: Run infection suite
                timeout-minutes: 10
                env:
                    STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
                run: composer infection
